In [40]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
from sklearn.externals import joblib
from sklearn import preprocessing

In [41]:
df =pd.read_csv("/home/nikhil/Desktop/Predicting-House-Prices-In-Bengaluru-Train-Data.csv")

In [42]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00

In [43]:
del df['availability']
del df['society']

In [44]:
df.head()

,area_type,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07
1,Plot Area,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00
2,Built-up Area,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00
3,Super built-up Area,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00
4,Super built-up Area,Kothanur,2 BHK,1200.0,2.0,1.0,51.00

In [45]:
df['bath'] = df['bath'].fillna(2.0)

In [46]:
df['balcony'] = df['balcony'].fillna(1)

In [47]:
df = df.dropna(how='any')

In [48]:
df.isnull().sum()

area_type     0
location      0
size          0
total_sqft    0
bath          0
balcony       0
price         0
dtype: int64

In [49]:
df.shape

(13302, 7)

In [50]:
df.head()

,area_type,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07
1,Plot Area,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00
2,Built-up Area,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00
3,Super built-up Area,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00
4,Super built-up Area,Kothanur,2 BHK,1200.0,2.0,1.0,51.00

In [51]:
features_df = pd.get_dummies(df, columns=['location','size','area_type'])

In [52]:
features_df

,total_sqft,bath,balcony,price,location_ Anekal,location_ Banaswadi,location_ Basavangudi,location_ Bhoganhalli,location_ Devarabeesana Halli,location_ Devarachikkanahalli,...,size_7 BHK,size_7 Bedroom,size_8 BHK,size_8 Bedroom,size_9 BHK,size_9 Bedroom,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,1056.0,2.0,1.0,39.07,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2600.0,5.0,3.0,120.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,1440.0,2.0,3.0,62.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,1521.0,3.0,1.0,95.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1200.0,2.0,1.0,51.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,1170.0,2.0,1.0,38.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,2732.0,4.0,1.0,204.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,3300.0,4.0,1.0,600.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,1310.0,3.0,1.0,63.25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,1020.0,6.0,1.0,370.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,1800.0,2.0,2.0,70.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,2785.0,5.0,3.0,295.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12,1000.0,2.0,1.0,38.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,1100.0,2.0,2.0,40.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,2250.0,3.0,2.0,148.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
15,1175.0,2.0,2.0,73.50,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,1180.0,3.0,2.0,48.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,1540.0,3.0,3.0,60.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,2770.0,4.0,2.0,290.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,1100.0,2.0,2.0,48.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20,600.0,1.0,1.0,15.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
21,1755.0,3.0,1.0,122.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
22,2800.0,5.0,2.0,380.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23,1767.0,3.0,1.0,103.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,510.0,1.0,0.0,25.25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,1250.0,3.0,2.0,56.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,660.0,1.0,1.0,23.10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,1610.0,3.0,2.0,81.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
28,1151.0,2.0,2.0,48.77,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
29,1025.0,2.0,1.0,47.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13289,4050.0,2.0,1.0,450.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13290,812.0,1.0,0.0,26.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13291,1440.0,2.0,2.0,63.93,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13292,2425.0,5.0,1.0,195.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13293,2200.0,3.0,3.0,80.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13294,1810.0,3.0,2.0,112.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13295,1200.0,2.0,2.0,140.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13296,1060.0,2.0,1.0,52.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13297,1015.0,2.0,2.0,60.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13298,2882.0,5.0,0.0,154.50,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13299,1500.0,6.0,2.0,145.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13300,1454.0,3.0,3.0,71.50,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13301,1075.0,2.0,2.0,48.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13302,774.0,5.0,3.0,70.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13303,1187.0,2.0,2.0,40.14,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13304,500.0,1.0,3.0,220.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13305,1200.0,5.0,1.0,325.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13306,1805.0,3.0,3.0,134.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13307,1527.0,3.0,1.0,142.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13308,1675.0,3.0,1.0,92.13,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13309,1050.0,2.0,2.0,52.71,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13310,1500.0,9.0,2.0,250.00,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
13311,1262.0,2.0,2.0,47.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13312,1345.0,2.0,1.0,57.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13313,1715.0,3.0,3.0,112.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13314,3453.0,4.0,0.0,231.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13315,3600.0,5.0,1.0,400.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13316,1141.0,2.0,1.0,60.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13317,4689.0,4.0,1.0,488.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13318,550.0,1.0,1.0,17.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [53]:
features_df.shape

(13302, 1343)

In [54]:
# Remove the sale price from the feature data
del features_df['price']

In [55]:
# Create the X and y arrays
X = features_df.as_matrix()
y = df['price'].as_matrix()

In [56]:
# Split the data set in a training set (70%) and a test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [57]:
# Fit regression model
model = ensemble.GradientBoostingRegressor(
    n_estimators=1000,
    learning_rate=0.1,
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss='huber',
    random_state=0
)

In [58]:
model.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='huber', max_depth=6,
             max_features=0.1, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=9, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=1000,
             presort='auto', random_state=0, subsample=1.0, verbose=0,
             warm_start=False)

In [59]:
# Save the trained model to a file so we can use it in other programs
joblib.dump(model, 'myhouseprice.pkl')

['myhouseprice.pkl']

In [60]:
# Find the error rate on the training set
mse = mean_absolute_error(y_train, model.predict(X_train))
print("Training Set Mean Absolute Error: %.4f" % mse)

Training Set Mean Absolute Error: 27.5019

In [61]:
# Find the error rate on the test set
mse = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: %.4f" % mse)

Test Set Mean Absolute Error: 30.6763